package main

import (
   "log"
   "net"
   "os"
   "bufio"
   "strings"
   "time"
   "strconv"
)

func main() {
	var node string
	var address string
	var port string
	if len(os.Args) > 1 {
		node = os.Args[1]
		address = os.Args[2]
		port = os.Args[3]
	}else {
		log.Fatal("Please enter the node number, address, port number in the command line")
	}

	log.Println(node, address, port)

   conn, err := net.Dial("tcp", address + ":" + port)
   if err != nil {
      log.Fatal("Connection Failed", err)
   }
   defer conn.Close()
   log.Println("Connection Successfully")
   // send message
   time := float64(time.Now().UnixNano())/float64(1000000000) // time (nanosec) -> float
   timestamp := strconv.FormatFloat(time, 'f', 9, 64) // float -> string
   conn.Write([]byte( timestamp + " - " + node + " connected"))

   	// read log generated by generator.py
	for{
		s := bufio.NewScanner(os.Stdin)
		for s.Scan() {
			parts := strings.Split(s.Text(), " ")
			conn.Write([]byte(parts[0] + " " + node + " " + parts[1]))
		}
	}
}